<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            [
                'email' => 'johndoe@example.com',
                'first_name' => 'John',
                'last_name' => 'Doe',
                'biography' => 'Amante del cine clásico y la fotografía urbana.',
                'phone' => '555-123-4567',
                'date_of_birth' => '1985-06-15',
                'country' => 'Estados Unidos',
                'picture' => 'https://picsum.photos/200/200?random=1',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'janedoe@example.com',
                'first_name' => 'Jane',
                'last_name' => 'Doe',
                'biography' => 'Apasionada por la literatura latinoamericana y el teatro independiente.',
                'phone' => '555-234-5678',
                'date_of_birth' => '1990-03-22',
                'country' => 'Argentina',
                'picture' => 'https://picsum.photos/200/200?random=2',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'carlosgarcia@example.com',
                'first_name' => 'Carlos',
                'last_name' => 'Garcia',
                'biography' => 'Músico aficionado, me encanta el jazz y el flamenco.',
                'phone' => '555-345-6789',
                'date_of_birth' => '1978-11-08',
                'country' => 'España',
                'picture' => 'https://picsum.photos/200/200?random=3',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'mariasanchez@example.com',
                'first_name' => 'Maria',
                'last_name' => 'Sanchez',
                'biography' => 'Entusiasta de la cultura japonesa, el anime y el manga.',
                'phone' => '555-456-7890',
                'date_of_birth' => '1995-07-02',
                'country' => 'Japón',
                'picture' => 'https://picsum.photos/200/200?random=4',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'peterjones@example.com',
                'first_name' => 'Peter',
                'last_name' => 'Jones',
                'biography' => 'Aficionado a la historia medieval y la arquitectura gótica.',
                'phone' => '555-567-8901',
                'date_of_birth' => '1982-04-29',
                'country' => 'Inglaterra',
                'picture' => 'https://picsum.photos/200/200?random=5',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'laurenbrown@example.com',
                'first_name' => 'Lauren',
                'last_name' => 'Brown',
                'biography' => 'Bailarina de ballet clásico, me fascina la música clásica y la ópera.',
                'phone' => '555-678-9012',
                'date_of_birth' => '1993-12-17',
                'country' => 'Francia',
                'picture' => 'https://picsum.photos/200/200?random=6',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'davidwilson@example.com',
                'first_name' => 'David',
                'last_name' => 'Wilson',
                'biography' => 'Escritor aficionado, me inspiran las culturas antiguas y la mitología.',
                'phone' => '555-789-0123',
                'date_of_birth' => '1988-09-05',
                'country' => 'Grecia',
                'picture' => 'https://picsum.photos/200/200?random=7',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'sophiamartin@example.com',
                'first_name' => 'Sophia',
                'last_name' => 'Martin',
                'biography' => 'Adoro viajar y conocer nuevas culturas, sobre todo a través de su gastronomía.',
                'phone' => '555-890-1234',
                'date_of_birth' => '1997-05-31',
                'country' => 'Italia',
                'picture' => 'https://picsum.photos/200/200?random=8',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'danielthompson@example.com',
                'first_name' => 'Daniel',
                'last_name' => 'Thompson',
                'biography' => 'Amante del arte callejero y la cultura urbana, me encanta el hip hop y el breakdance.',
                'phone' => '555-901-2345',
                'date_of_birth' => '1991-02-18',
                'country' => 'Estados Unidos',
                'picture' => 'https://picsum.photos/200/200?random=9',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'emilydavis@example.com',
                'first_name' => 'Emily',
                'last_name' => 'Davis',
                'biography' => 'Diseñadora gráfica, apasionada por la ilustración y la tipografía.',
                'phone' => '555-012-3456',
                'date_of_birth' => '1989-10-26',
                'country' => 'Inglaterra',
                'picture' => 'https://picsum.photos/200/200?random=10',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'alejandrorodriguez@example.com',
                'first_name' => 'Alejandro',
                'last_name' => 'Rodriguez',
                'biography' => 'Me encanta la música latina, desde la salsa hasta el tango.',
                'phone' => '555-123-4567',
                'date_of_birth' => '1987-08-12',
                'country' => 'Colombia',
                'picture' => 'https://picsum.photos/200/200?random=11',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'isabelfernandez@example.com',
                'first_name' => 'Isabel',
                'last_name' => 'Fernandez',
                'biography' => 'Amante del arte surrealista y la fotografía de naturaleza.',
                'phone' => '555-234-5678',
                'date_of_birth' => '1992-05-04',
                'country' => 'España',
                'picture' => 'https://picsum.photos/200/200?random=12',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'thomasmuller@example.com',
                'first_name' => 'Thomas',
                'last_name' => 'Muller',
                'biography' => 'Me fascina la historia del arte, desde el Renacimiento hasta el arte moderno.',
                'phone' => '555-345-6789',
                'date_of_birth' => '1984-09-21',
                'country' => 'Alemania',
                'picture' => 'https://picsum.photos/200/200?random=13',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'chloelefebvre@example.com',
                'first_name' => 'Chloé',
                'last_name' => 'Lefebvre',
                'biography' => 'Apasionada por la moda y la cultura francesa, me encanta el cine de la Nouvelle Vague.',
                'phone' => '555-456-7890',
                'date_of_birth' => '1996-11-14',
                'country' => 'Francia',
                'picture' => 'https://picsum.photos/200/200?random=14',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'luigirusso@example.com',
                'first_name' => 'Luigi',
                'last_name' => 'Russo',
                'biography' => 'Chef profesional, me encanta descubrir nuevos sabores e ingredientes.',
                'phone' => '555-567-8901',
                'date_of_birth' => '1980-07-09',
                'country' => 'Italia',
                'picture' => 'https://picsum.photos/200/200?random=15',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'annakowalczyk@example.com',
                'first_name' => 'Anna',
                'last_name' => 'Kowalczyk',
                'biography' => 'Me encanta la fotografía de viajes y documentar mis experiencias culturales.',
                'phone' => '555-678-9012',
                'date_of_birth' => '1994-03-06',
                'country' => 'Polonia',
                'picture' => 'https://picsum.photos/200/200?random=16',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'jameslee@example.com',
                'first_name' => 'James',
                'last_name' => 'Lee',
                'biography' => 'Fanático de la ciencia ficción y la tecnología, me interesa la cultura digital.',
                'phone' => '555-789-0123',
                'date_of_birth' => '1983-12-25',
                'country' => 'Corea del Sur',
                'picture' => 'https://picsum.photos/200/200?random=17',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'elenavasquez@example.com',
                'first_name' => 'Elena',
                'last_name' => 'Vasquez',
                'biography' => 'Amante del baile flamenco y la música española, me gusta la poesía y el teatro clásico.',
                'phone' => '555-890-1234',
                'date_of_birth' => '1998-08-19',
                'country' => 'España',
                'picture' => 'https://picsum.photos/200/200?random=18',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'mohammedali@example.com',
                'first_name' => 'Mohammed',
                'last_name' => 'Ali',
                'biography' => 'Interesado en la caligrafía árabe, la música tradicional y la literatura del Medio Oriente.',
                'phone' => '555-901-2345',
                'date_of_birth' => '1986-04-03',
                'country' => 'Marruecos',
                'picture' => 'https://picsum.photos/200/200?random=19',
                'password' => 'randomPass321',
            ],
            [
                'email' => 'sofiapetrova@example.com',
                'first_name' => 'Sofia',
                'last_name' => 'Petrova',
                'biography' => 'Me apasiona la cultura rusa, el ballet clásico, la literatura y la música folclórica.',
                'phone' => '555-012-3456',
                'date_of_birth' => '1990-06-27',
                'country' => 'Rusia',
                'picture' => 'https://picsum.photos/200/200?random=20',
                'password' => 'randomPass321',
            ],
        ];

        foreach ($users as $user) {
            $user['password'] = bcrypt($user['password']);
            $user['created_at'] = rand(1, 20) > 10 ? now() : now()->subDays(rand(1, 30));
            \App\Models\User::create($user);
            
        }
    }
}
